### ISSUE TITLE
Restoration Docker/UI

### ISSUE THREAD

**Issue by adlp** [cyborgbackup/cyborgbackup#79]
Hello,

I don't see this issue not like a true one, sorry :(
So my question is : "I'm using CyborgBackup-UI (developp version) with docker, I would like to do some restoration through the UI, with docker server (or api) version I've to choose ?"

Thanks ;)
Antoine.

**Comment by GaetanF** [comment]
Hello,

The docker version is very instable for the moment. From memory, the Pull backup method and restoration and Catalog have some issues on this version. I will check them next week if I can fix something.

**Comment by dwlodarczyk13** [comment]
This made me actually curious, and bit worried since I want to use `cyborg` as main backup tool for my projects.

Do i get it correctly that restoring backup is actually not working if using docker?

I'm using these images:
```
  callback_receiver:
    image: cyborgbackup/cyborgbackup:latest
  channel_workers:
    image: cyborgbackup/cyborgbackup:latest
  api:
    image: cyborgbackup/cyborgbackup:latest
  celery:
    image: cyborgbackup/cyborgbackup:latest
  celery_beat:
    image: cyborgbackup/cyborgbackup:latest
  ui:
    image: cyborgbackup/cyborgbackup-ui:develop
```
